### ISSUE TITLE
Request Failed

### ISSUE THREAD

**Issue by chengxingen** [google-pay/android-quickstart#11]
I integrated Google Payments on the Android client, and everything was documented, but when the payment was called, the client prompted "This merchant is not enabled for Google Pay," used "adb-d logcat-s Wallet Merchant Error" on the command line, and promte "Wallet Merchant Error: Error in loadPayment Data: You have not registered" Red to use this API. Double check your Android app or app ". 

I've searched for a long time, but I don't know where the problem is. 
I need help, thanks , thanks

**Comment by subhash4android** [comment]
<meta-data
            android:name="com.google.android.gms.wallet.api.enabled"
            android:value="true" />

Check whether the above code is added in manifest file or not.
Add in manifest file, hope it will work.

**Comment by fstanis** [comment]
Please see the [Troubleshooting - Registration and access](https://developers.google.com/pay/api/android/support/troubleshooting#registration-access) section of the documentation - this issue tracker is reserved for issues with the sample itself.
