### ISSUE TITLE
Crashes when going back

### ISSUE THREAD

**Issue by GalatiaPar** [google-pay/android-quickstart#15]
I clicked on G Pay button, and then clicked back. The app keeps on crashing every time I do this. 
Used the kotlin example.

**Device information:**
Android Pie 9.0
Pixel 2 XL

**Comment by JlUgia** [comment]
Thank you for the feedback @GalatiaPar.
The issue was acknowledged and fixed on #14.
Closing this issue. Feel free to re-open if the problem persists.
