### ISSUE TITLE
payment method error

### ISSUE THREAD

**Issue by knoxcard** [google-pay/android-quickstart#8]
The payment handler "https://pay.google.com/gp/p/" is not allowed to use payment method "https://google.com/pay", because the payment handler origin "https://pay.google.com/" is different from the payment method origin "https://google.com/" and the "supported_origins" field in the payment method manifest for "https://google.com/pay" is not "*" and is not a list that includes "https://pay.google.com/".

**Comment by florinfm** [comment]
Can you please provide more details.
Thanks
